# Copyright 2021 Nordcloud Oy or its affiliates. All Rights Reserved.

name:  Terraform Git Ops
on:
  push:
    branches:
      - master
    paths:
      - "${TTERRAFORM_BASE_DIR}/**.tf"
defaults:
  run:
    shell: bash
env:
  TERRAFORM_BASE_DIR: 'terraform'
jobs:
  get_changed_directories:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed_directories.outputs.matrix }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: changed_directories
        run: |
          DIRS=$( git --no-pager diff --name-only HEAD~1 | grep ${TERRAFORM_BASE_DIR} )
          JQ_LIST=$( jq -ncR '[inputs]' <<< ${DIRS} )
          echo ${JQ_LIST}
          echo "::set-output name=matrix::${DIRS}"
  git-ops:
    runs-on: ubuntu-latest
    needs: get_changed_directories
    strategy:
    #   fail-fast: false
      matrix:
          # directories: ${{needs.get_changed_directories.outputs.matrix}}
          directories: ["terraform/rg_1", "terraform/rg_2"]
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.directories }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: changed files
        run: echo $(ls -la)
  # terraform-plan:
  #   runs-on: ubuntu-latest
  #   env:
  #     TF_CLI_ARGS: '-no-color'
  #     ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  #     ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  #     ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  #     ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  #     TFVARS_FILE_PATH: ./project_spaces
  #   steps:
  #     - name: Checkout Source Code
  #       uses: actions/checkout@v2
  #     - name: Install Terraform
  #       uses: hashicorp/setup-terraform@v1
  #       with:
  #         terraform_wrapper: false
  #     - name: Login via Az module
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{secrets.AZURE_CREDENTIALS}}
  #     - name: Terraform fmt
  #       run: terraform fmt -check
  #     - name: Terraform Init
  #       run: |
  #         terraform init
  #     - name: Terraform Validate
  #       id: validate
  #       run: terraform validate
  #     - name: Terraform Set Subcription
  #       run: |
  #         terraform apply -auto-approve -target=module.subscription -var-file="${{ env.TFVARS_FILE_PATH }}/${{ github.event.inputs.environment_name }}.tfvars"
  #         echo "ARM_SUBSCRIPTION_ID=$(terraform output -raw subscription_id)" >> $GITHUB_ENV
  #     - name: Terraform Apply
  #       run: terraform apply -auto-approve -var-file="${{ env.TFVARS_FILE_PATH }}/${{ github.event.inputs.environment_name }}.tfvars"
  #     - name: Terraform Force Copy
  #       run: terraform init -force-copy
  # terraform-apply:
  #   runs-on: ubuntu-latest
  #   env:
  #     TF_CLI_ARGS: '-no-color'
  #     ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  #     ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  #     ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  #     ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  #     TFVARS_FILE_PATH: ./project_spaces
  #   steps:
  #     - name: Checkout Source Code
  #       uses: actions/checkout@v2
  #     - name: Install Terraform
  #       uses: hashicorp/setup-terraform@v1
  #       with:
  #         terraform_wrapper: false
  #     - name: Login via Az module
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{secrets.AZURE_CREDENTIALS}}
  #     - name: Terraform fmt
  #       run: terraform fmt -check
  #     - name: Terraform Init
  #       run: |
  #         terraform init
  #     - name: Terraform Validate
  #       id: validate
  #       run: terraform validate
  #     - name: Terraform Set Subcription
  #       run: |
  #         terraform apply -auto-approve -target=module.subscription -var-file="${{ env.TFVARS_FILE_PATH }}/${{ github.event.inputs.environment_name }}.tfvars"
  #         echo "ARM_SUBSCRIPTION_ID=$(terraform output -raw subscription_id)" >> $GITHUB_ENV
  #     - name: Terraform Apply
  #       run: terraform apply -auto-approve -var-file="${{ env.TFVARS_FILE_PATH }}/${{ github.event.inputs.environment_name }}.tfvars"
  #     - name: Terraform Force Copy
  #       run: terraform init -force-copy
