# Copyright 2021 Nordcloud Oy or its affiliates. All Rights Reserved.

name:  Terraform Git Ops
on:
  push:
    branches:
      - master
    paths:
      - 'terraform/**.tf'
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: changed files
        run: echo $( git --no-pager diff --name-only FETCH_HEAD~1 )
  # terraform-plan:
  #   runs-on: ubuntu-latest
  #   env:
  #     TF_CLI_ARGS: '-no-color'
  #     ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  #     ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  #     ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  #     ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  #     TFVARS_FILE_PATH: ./project_spaces
  #   steps:
  #     - name: Checkout Source Code
  #       uses: actions/checkout@v2
  #     - name: Install Terraform
  #       uses: hashicorp/setup-terraform@v1
  #       with:
  #         terraform_wrapper: false
  #     - name: Login via Az module
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{secrets.AZURE_CREDENTIALS}}
  #     - name: Terraform fmt
  #       run: terraform fmt -check
  #     - name: Terraform Init
  #       run: |
  #         terraform init
  #     - name: Terraform Validate
  #       id: validate
  #       run: terraform validate
  #     - name: Terraform Set Subcription
  #       run: |
  #         terraform apply -auto-approve -target=module.subscription -var-file="${{ env.TFVARS_FILE_PATH }}/${{ github.event.inputs.environment_name }}.tfvars"
  #         echo "ARM_SUBSCRIPTION_ID=$(terraform output -raw subscription_id)" >> $GITHUB_ENV
  #     - name: Terraform Apply
  #       run: terraform apply -auto-approve -var-file="${{ env.TFVARS_FILE_PATH }}/${{ github.event.inputs.environment_name }}.tfvars"
  #     - name: Terraform Force Copy
  #       run: terraform init -force-copy
  # terraform-apply:
  #   runs-on: ubuntu-latest
  #   env:
  #     TF_CLI_ARGS: '-no-color'
  #     ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  #     ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  #     ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  #     ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  #     TFVARS_FILE_PATH: ./project_spaces
  #   steps:
  #     - name: Checkout Source Code
  #       uses: actions/checkout@v2
  #     - name: Install Terraform
  #       uses: hashicorp/setup-terraform@v1
  #       with:
  #         terraform_wrapper: false
  #     - name: Login via Az module
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{secrets.AZURE_CREDENTIALS}}
  #     - name: Terraform fmt
  #       run: terraform fmt -check
  #     - name: Terraform Init
  #       run: |
  #         terraform init
  #     - name: Terraform Validate
  #       id: validate
  #       run: terraform validate
  #     - name: Terraform Set Subcription
  #       run: |
  #         terraform apply -auto-approve -target=module.subscription -var-file="${{ env.TFVARS_FILE_PATH }}/${{ github.event.inputs.environment_name }}.tfvars"
  #         echo "ARM_SUBSCRIPTION_ID=$(terraform output -raw subscription_id)" >> $GITHUB_ENV
  #     - name: Terraform Apply
  #       run: terraform apply -auto-approve -var-file="${{ env.TFVARS_FILE_PATH }}/${{ github.event.inputs.environment_name }}.tfvars"
  #     - name: Terraform Force Copy
  #       run: terraform init -force-copy
